// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLfby4M8s3xq1umEcj_VB8umayTJnCdYE',
    appId: '1:627695306168:web:3d30921d0466e9d2bfbb4d',
    messagingSenderId: '627695306168',
    projectId: 'instagram-2a149',
    authDomain: 'instagram-2a149.firebaseapp.com',
    storageBucket: 'instagram-2a149.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1gB4AGde2bkQhM6dQwh2CD8hPVSNQoaU',
    appId: '1:627695306168:android:b942be0130dd3b91bfbb4d',
    messagingSenderId: '627695306168',
    projectId: 'instagram-2a149',
    storageBucket: 'instagram-2a149.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtV4csdXDOrUABcOcSnN75CFfQG5EHcvE',
    appId: '1:627695306168:ios:636fe62cec8833babfbb4d',
    messagingSenderId: '627695306168',
    projectId: 'instagram-2a149',
    storageBucket: 'instagram-2a149.firebasestorage.app',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtV4csdXDOrUABcOcSnN75CFfQG5EHcvE',
    appId: '1:627695306168:ios:636fe62cec8833babfbb4d',
    messagingSenderId: '627695306168',
    projectId: 'instagram-2a149',
    storageBucket: 'instagram-2a149.firebasestorage.app',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLfby4M8s3xq1umEcj_VB8umayTJnCdYE',
    appId: '1:627695306168:web:198e81ac5175a338bfbb4d',
    messagingSenderId: '627695306168',
    projectId: 'instagram-2a149',
    authDomain: 'instagram-2a149.firebaseapp.com',
    storageBucket: 'instagram-2a149.firebasestorage.app',
  );

}